import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const webStreamShim = {
	name: 'web-stream-shim',
	setup(build) {
		build.onResolve({ filter: /^(node:)?stream\/web$/ }, args => ({
			path: args.path,
			namespace: 'web-stream-shim',
		}));
		build.onLoad({ filter: /.*/, namespace: 'web-stream-shim' }, () => ({
			contents: `
				export const ReadableStream = globalThis.ReadableStream;
				export const WritableStream = globalThis.WritableStream;
				export const TransformStream = globalThis.TransformStream;
				export const ByteLengthQueuingStrategy = globalThis.ByteLengthQueuingStrategy;
				export const CountQueuingStrategy = globalThis.CountQueuingStrategy;
				export const TextEncoderStream = globalThis.TextEncoderStream;
				export const TextDecoderStream = globalThis.TextDecoderStream;
				export default {
					ReadableStream,
					WritableStream,
					TransformStream,
					ByteLengthQueuingStrategy,
					CountQueuingStrategy,
					TextEncoderStream,
					TextDecoderStream,
				};
			`,
		}));
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	plugins: [webStreamShim],
	platform: 'node',
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}